server:
  port: 8085

---

custom:
  security:
    jwt:
      secret: password

---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://172.25.0.2:5432/housingdb}
    username: dmcs
    password: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  queries:
    users-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
