server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB:jdbc:postgresql://localhost:5432/housingdb}
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
