server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB:jdbc:postgresql://172.25.0.2:5432/housingdb}
    username: dmcs
    password: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update