server:
  port: 8093

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB:jdbc:postgresql://localhost:5432/userdetails}
    username: dmcs
    password: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update